sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t rahulpol/react-test ./client

script:
  - docker run -e CI=true rahulpol/react-test npm run test

after_success:
  - docker build -t rahulpol/multi-client ./client
  - docker build -t rahulpol/multi-nginx ./nginx
  - docker build -t rahulpol/multi-server ./server
  - docker build -t rahulpol/multi-worker ./worker
  # Log in docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push rahulpol/multi-client
  - docker push rahulpol/multi-nginx
  - docker push rahulpol/multi-server
  - docker push rahulpol/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-314008291062'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
